name: SCIPYLAZZ2016
channels:
    - conda-forge
dependencies:
    - python=3.6
    - basemap
    - basemap-data-hires
    - cartopy
    - ctd
    - cython
    - dask
    - descartes
    - fiona
    - folium
    - fortran-magic
    - geojson
    - geojsonio
    - geopandas
    - gsw
    - iris
    - jupyter
    - matplotlib
    - numba
    - numpy
    - oceans
    - oct2py
    - pandas
    - pyproj
    - r-essentials
    - r-oce
    - rasterio
    - requests
    - rpy2
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - statsmodels
    - sympy
    - xlrd
    - xarray
